apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-docker-deployment
  labels:
    app: jenkins-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-docker
  template:
    metadata:
      labels:
        app: jenkins-docker
    spec:
      containers:
      - name: jenkins-docker
        image: kranthi193/jenkins-docker-nginx:11
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-docker-service
spec:
  type: NodePort
  selector:
    app: jenkins-docker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
